variables:
  AUTO_DEVOPS_EXPLICITLY_DISABLED: "1"

include: []

stages:
  - deploy

deploy_production:
  stage: deploy
  image: docker:cli
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache git docker-compose
  script:
    - docker-compose -f docker-compose.yml up -d --build
    - docker exec weamis-money-app php artisan migrate --force
    - docker exec weamis-money-app chmod -R 777 storage bootstrap/cache database || true
    - docker exec weamis-money-app php artisan config:clear
    - docker exec weamis-money-app php artisan cache:clear
    - docker exec weamis-money-app php artisan view:clear


